### ISSUE TITLE
throw warning when eval_time isn't needed

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#704]
These functions should warn (but not error) when `eval_time` is _not_ `NULL` in the following cases:

For  non-survival models and for survival models with a static metric
- [x] `fit_resamples()` 
- [x] `tune_grid()` 
- [x] `tune_bayes()` 
- [x] `tune_race_anova()` works but https://github.com/tidymodels/finetune/issues/91
- [x] `tune_race_win_loss()` https://github.com/tidymodels/finetune/issues/92
- [x] `tune_sim_anneal()`

For non-survival models and for survival models _without_ a dynamic metric
- [x] `show_best()`and `select_best()` work but message text is not as closely aligned as it could be https://github.com/tidymodels/tune/issues/811
- [x] `select_by_one_std_err()`and `select_by_pct_loss()` use `choose_eval_time()`, thus same comment as `select_best()`
- [x] `autoplot()` #706
- [x] `int_pctl()`
- [x] `fit_best()`

And bringing it all together: https://github.com/tidymodels/tune/issues/811

And the exception, for consistency within the function (with how the choice of metric is treated)
- [x] `augment()` should not take an eval_time arg 

----

`show_best()` should throw a warning if `eval_time` is used but the metric selected is not dynamic. See last line: 

``` r
library(tidymodels)
library(censored)
#> Loading required package: survival
```

``` r

tidymodels_prefer()
theme_set(theme_bw())
options(pillar.advice = FALSE, pillar.min_title_chars = Inf)
```

``` r


data("mlc_churn")

mlc_churn <-
  mlc_churn %>%
  mutate(
    churned = ifelse(churn == "yes", 1, 0),
    event_time = Surv(account_length, churned)
  ) %>%
  select(event_time, account_length, voice_mail_plan) %>%
  slice(1:500)

set.seed(6941)
churn_split <- initial_split(mlc_churn, prop = 4/5)
churn_tr <- training(churn_split)
churn_te <- testing(churn_split)
churn_rs <- bootstraps(churn_tr, times = 2)
```

``` r

sr_tune_spec <- survival_reg(dist = tune())
eval_times <- c(10, 100, 150)
event_metrics <- metric_set(brier_survival, brier_survival_integrated,
                            concordance_survival, roc_auc_survival)
sr_grid <- tibble(dist = c("loglogistic", "lognormal"))
```

``` r

sr_tune_res <-
  sr_tune_spec %>%
  tune_grid(
    event_time ~ .,
    resamples = churn_rs,
    metrics = event_metrics,
    eval_time = eval_times,
    grid = sr_grid,
    control = control_grid(save_pred = TRUE)
  )
```

``` r

# Eval time isn't used and we should throw a warning
show_best(sr_tune_res, metric = "brier_survival_integrated", eval_time = 10)
#> # A tibble: 2 × 8
#>   dist        .metric         .estimator .eval_time   mean     n std_err .config
#>   <chr>       <chr>           <chr>           <dbl>  <dbl> <int>   <dbl> <chr>  
#> 1 loglogistic brier_survival… standard           NA 0.0282     2 0.00591 Prepro…
#> 2 lognormal   brier_survival… standard           NA 0.0399     2 0.00479 Prepro…
```

<sup>Created on 2023-07-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hfrick** [comment]
Same for `select_best()`, `select_by_one_std_err()` and `select_by_pct_loss()`

**Comment by hfrick** [comment]
Also to look into: `autoplot()`

**Comment by hfrick** [comment]
The tuning functions and `fit_resamples()` currently error when supplying `eval_time` for a static survival metric and for non-censored-regression models in general.  Should they also warn instead?

**Comment by topepo** [comment]
I think that it should be a warning. It is unneeded but won't cause bad results.
