### ISSUE TITLE
When we need to default to a single value for `eval_time`

### ISSUE THREAD

**Issue by hfrick** [tidymodels/tune#766]
[Using this issue as the epic] 

Update (moved up here from https://github.com/tidymodels/tune/issues/766#issuecomment-1893596462 for better visibility)

- [x] `show_best()`: majority done, polishing required in https://github.com/tidymodels/tune/issues/781 and https://github.com/tidymodels/finetune/issues/89
- [x] `select_*()`: currently in sync wit `show_best()` by either calling it directly (`select_best()`) or calling `choose_eval_time()` like `show_best()` (the other `select_*()` functions)
- [x] `autoplot()`: needs to switch to using the first one https://github.com/tidymodels/tune/issues/808
- [x] `int_pctl()`: needs to switch to using the first one, plus something is broken now https://github.com/tidymodels/tune/issues/809
- [x] `augment()`: should not warn but use the first one quietly https://github.com/tidymodels/tune/issues/810
- [x] `fit_best()`: done in https://github.com/tidymodels/tune/pull/797

----

We allow `eval_time` to be a vector of time point for the tuning functions, also because the integrated survival metrics need multiple evaluation time points.

However, if we are optimizing for a dynamic metric (rather than integrated, or static) we are using the _first_ value of `eval_time` as the time point to calculate the metric at. 

We have a couple of other situations where we need to pick a single value for `eval_time` and we should do that consistently. The suggestion is to follow the logic of the tuning functions and pick the first value.

This affects the following functions if `eval_time = NULL`
- `show_best()`
- `select_*()`
- `autoplot()`
- `int_pctl()`

This also affects functions making use of `select_best()` in case the model choice is left unspecified
- `augment()`: no explict argument for `eval_time`. We should make a choice for `eval_time` like we do for the metric. That choice should be consistent with how we choose elsewhere.
- `fit_best()` also does not have an `eval_time` argument but does have a `metric` arg which defaults to the first metric if `NULL`

Note the inconsistency between `augment()` and `fit_best()` in terms of metrics argument here. 

``` r
library(tidymodels)
library(censored)
#> Loading required package: survival

set.seed(1)
sim_dat <- prodlim::SimSurv(500) %>%
  mutate(event_time = Surv(time, event)) %>%
  select(event_time, X1, X2) %>%
  as_tibble()

set.seed(2)
sim_rs <- vfold_cv(sim_dat)

time_points <- c(10, 1, 5, 15)

mod_spec <-
  proportional_hazards(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet") %>%
  set_mode("censored regression")

grid <- tibble(penalty = 10^c(-4, -2, -1))

gctrl <- control_grid(save_pred = TRUE, save_workflow = TRUE)

mix_mtrc <- metric_set(brier_survival, brier_survival_integrated, concordance_survival)

set.seed(2193)
tune_res <-
  mod_spec %>%
  tune_grid(
    event_time ~ X1 + X2,
    resamples = sim_rs,
    grid = grid,
    metrics = mix_mtrc,
    eval_time = time_points,
    control = gctrl
  )


# `eval_time` across different functions --------------------------------

res <- show_best(tune_res)
#> Warning: No value of `metric` was given; metric 'brier_survival' will be used.
#> Warning: No evaluation time was set; a value of 5 was used.

res <- select_best(tune_res)
#> Warning: No value of `metric` was given; metric 'brier_survival' will be used.
#> No evaluation time was set; a value of 5 was used.

res <- select_by_one_std_err(tune_res, penalty)
#> Warning: No value of `metric` was given; metric 'brier_survival' will be used.
#> No evaluation time was set; a value of 5 was used.

res <- select_by_pct_loss(tune_res, penalty)
#> Warning: No value of `metric` was given; metric 'brier_survival' will be used.
#> No evaluation time was set; a value of 5 was used.

res <- autoplot(tune_res)
#> Warning in filter_plot_eval_time(dat, eval_time): No evaluation time was set; a
#> value of 5 was used.

res <- int_pctl(tune_res)
#> Warning in int_pctl(tune_res): No evaluation time was set; a value of 5 was
#> used.

res <- augment(tune_res)
#> Warning: No evaluation time was set; a value of 5 was used.

res <- fit_best(tune_res)
#> Warning: No evaluation time was set; a value of 5 was used.
```

<sup>Created on 2023-11-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hfrick** [comment]
Note the inconsistency between `show_best()` and the `select_*()` functions in terms of "No evaluation time was set [...]" being a warning vs a message.

Another related issue: What to do when `eval_time` is supplied for a metric that doesn't need it (anymore)  #704

**Comment by hfrick** [comment]
Collecting occurrences in the code related to this topic:

`default_eval_time()`
https://github.com/tidymodels/tune/blob/35095777d21c582f7666dbf7520672ffd8cd2778/R/plots.R#L161-L174

`get_metric_time()`
https://github.com/tidymodels/tune/blob/35095777d21c582f7666dbf7520672ffd8cd2778/R/grid_helpers.R#L142-L150

**Comment by hfrick** [comment]
Update:

- [ ] `show_best()`: majority done, polishing required in https://github.com/tidymodels/tune/issues/781 and https://github.com/tidymodels/finetune/issues/89
- [ ] `select_*()`: currently in sync wit `show_best()` by either calling it directly (`select_best()`) or calling `choose_eval_time()` like `show_best()` (the other `select_*()` functions)
- [ ] `autoplot()`: needs to switch to using the first one https://github.com/tidymodels/tune/issues/808
- [ ] `int_pctl()`: needs to switch to using the first one, plus something is broken now https://github.com/tidymodels/tune/issues/809
- [ ] `augment()`: should not warn but use the first one quietly https://github.com/tidymodels/tune/issues/810
- [x] `fit_best()`: done in https://github.com/tidymodels/tune/pull/797

``` r
library(tidymodels)
library(censored)
#> Loading required package: survival

set.seed(1)
sim_dat <- prodlim::SimSurv(500) %>%
  mutate(event_time = Surv(time, event)) %>%
  select(event_time, X1, X2) %>%
  as_tibble()

set.seed(2)
sim_rs <- vfold_cv(sim_dat)

time_points <- c(10, 1, 5, 15)

mod_spec <-
  proportional_hazards(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet") %>%
  set_mode("censored regression")

grid <- tibble(penalty = 10^c(-4, -2, -1))

gctrl <- control_grid(save_pred = TRUE, save_workflow = TRUE)

mix_mtrc <- metric_set(brier_survival, brier_survival_integrated, concordance_survival)

set.seed(2193)
tune_res <-
  mod_spec %>%
  tune_grid(
    event_time ~ X1 + X2,
    resamples = sim_rs,
    grid = grid,
    metrics = mix_mtrc,
    eval_time = time_points,
    control = gctrl
  )


# `eval_time` across different functions --------------------------------

res <- show_best(tune_res)
#> Warning in show_best(tune_res): No value of `metric` was given;
#> "brier_survival" will be used.
#> Warning: 4 evaluation times are available; the first (10) will be used.

res <- select_best(tune_res)
#> Warning in select_best(tune_res): No value of `metric` was given; "brier_survival" will be used.
#> 4 evaluation times are available; the first (10) will be used.

res <- select_by_one_std_err(tune_res, penalty)
#> Warning in select_by_one_std_err(tune_res, penalty): No value of `metric` was given; "brier_survival" will be used.
#> 4 evaluation times are available; the first (10) will be used.

res <- select_by_pct_loss(tune_res, penalty)
#> Warning in select_by_pct_loss(tune_res, penalty): No value of `metric` was given; "brier_survival" will be used.
#> 4 evaluation times are available; the first (10) will be used.

res <- autoplot(tune_res)
#> Warning in filter_plot_eval_time(dat, eval_time): No evaluation time was set; a
#> value of 5 was used.

res <- int_pctl(tune_res)
#> Warning in int_pctl(tune_res): No evaluation time was set; a value of 5 was
#> used.
#> Error in `purrr::map2()`:
#> ℹ In index: 1.
#> Caused by error in `dplyr::rename()`:
#> ! Can't rename columns that don't exist.
#> ✖ Column `term` doesn't exist.

res <- augment(tune_res)
#> Warning: 4 evaluation times are available; the first (10) will be used.

res <- fit_best(tune_res)
```

<sup>Created on 2024-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hfrick** [comment]
Done! 🎉
